chore: debug pre-push hook

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,15 +1,44 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-export PATH="/c/Program Files/nodejs:$NVM_HOME:$PATH" 
+# Ensure Node.js is in the PATH
+export PATH="/c/Program Files/nodejs:$NVM_HOME:$NVM_SYMLINK:$PATH"
+
+# Debug: Print updated PATH
+echo "Updated PATH: $PATH"
 
 # Get the last commit message
 last_commit_message=$(git log -1 --pretty=%B)
+
+# Debug: Print the last commit message
+echo "Last commit message: $last_commit_message"
 
 # Check if the commit message contains #skip_publish
 if echo "$last_commit_message" | grep -q "#skip_publish"; then
     echo "Skipping version check due to #skip_publish in the commit message."
     exit 0
 else
+    echo "Running version check..."
     node .husky/scripts/check-version.js
+    # Debug: Check the exit status of the node command
+    echo "check-version.js exit status: $?"
 fi
+
+
+
+
+# #!/bin/sh
+# . "$(dirname "$0")/_/husky.sh"
+
+# export PATH="/c/Program Files/nodejs:$NVM_HOME:$PATH" 
+
+# # Get the last commit message
+# last_commit_message=$(git log -1 --pretty=%B)
+
+# # Check if the commit message contains #skip_publish
+# if echo "$last_commit_message" | grep -q "#skip_publish"; then
+#     echo "Skipping version check due to #skip_publish in the commit message."
+#     exit 0
+# else
+#     node .husky/scripts/check-version.js
+# fi
